// <auto-generated />
using Hogwarts.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hogwarts.Api.Migrations
{
    [DbContext(typeof(HogwartsDbContext))]
    [Migration("20200923192106_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hogwarts.Data.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortHandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 0,
                            Name = "History of Magic"
                        },
                        new
                        {
                            Id = 2,
                            Level = 1,
                            Name = "Muggle Studies"
                        },
                        new
                        {
                            Id = 3,
                            Level = 0,
                            Name = "Transfiguration"
                        },
                        new
                        {
                            Id = 4,
                            Level = 1,
                            Name = "Care of Magical Creatures"
                        },
                        new
                        {
                            Id = 5,
                            Level = 0,
                            Name = "Defence Against the Dark Arts"
                        },
                        new
                        {
                            Id = 6,
                            Level = 2,
                            Name = "Flying"
                        },
                        new
                        {
                            Id = 7,
                            Level = 0,
                            Name = "Charms"
                        },
                        new
                        {
                            Id = 8,
                            Level = 0,
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = 9,
                            Level = 1,
                            Name = "Divination"
                        },
                        new
                        {
                            Id = 10,
                            Level = 0,
                            Name = "Herbology"
                        },
                        new
                        {
                            Id = 11,
                            Level = 1,
                            Name = "Divination"
                        },
                        new
                        {
                            Id = 12,
                            Level = 0,
                            Name = "Potions"
                        },
                        new
                        {
                            Id = 13,
                            Level = 1,
                            Name = "Alchemy"
                        },
                        new
                        {
                            Id = 14,
                            Level = 1,
                            Name = "Arithmancy"
                        },
                        new
                        {
                            Id = 15,
                            Level = 1,
                            Name = "Study of Ancient Runes"
                        },
                        new
                        {
                            Id = 16,
                            Level = 2,
                            Name = "Apparition"
                        },
                        new
                        {
                            Id = 17,
                            Level = 2,
                            Name = "Advanced Arithmancy Studies"
                        },
                        new
                        {
                            Id = 18,
                            Level = 2,
                            Name = "Ancient Studies"
                        },
                        new
                        {
                            Id = 19,
                            Level = 2,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 20,
                            Level = 2,
                            Name = "Ghoul Studies"
                        },
                        new
                        {
                            Id = 21,
                            Level = 2,
                            Name = "Magical Theory"
                        },
                        new
                        {
                            Id = 22,
                            Level = 2,
                            Name = "Muggle Art"
                        },
                        new
                        {
                            Id = 23,
                            Level = 2,
                            Name = "Muggle Music"
                        },
                        new
                        {
                            Id = 24,
                            Level = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 25,
                            Level = 2,
                            Name = "Xylomancy"
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.HeadOfHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("StaffId");

                    b.ToTable("HeadOfHouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseId = 1,
                            StaffId = 1
                        },
                        new
                        {
                            Id = 2,
                            HouseId = 1,
                            StaffId = 2
                        },
                        new
                        {
                            Id = 3,
                            HouseId = 2,
                            StaffId = 4
                        },
                        new
                        {
                            Id = 4,
                            HouseId = 2,
                            StaffId = 14
                        },
                        new
                        {
                            Id = 5,
                            HouseId = 4,
                            StaffId = 9
                        },
                        new
                        {
                            Id = 6,
                            HouseId = 3,
                            StaffId = 16
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MascotImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MascotImageLink = "https://cdn.europosters.eu/image/1300/metal-tin-sign/harry-potter-gryffindor-i72420.jpg",
                            Name = "Gryffindor"
                        },
                        new
                        {
                            Id = 2,
                            MascotImageLink = "https://t0.gstatic.com/images?q=tbn%3AANd9GcQTrAsIK_l-uPN1c1Wo5jJK5PJ1xaFDonGcU9MyMRCeSe0gSr2nucmNf2N10L4RIP6InShl4K-G&usqp=CAc",
                            Name = "Slytherin"
                        },
                        new
                        {
                            Id = 3,
                            MascotImageLink = "https://s1.thcdn.com/productimg/1600/1600/12024631-1474653879765789.jpg",
                            Name = "Hufflepuff"
                        },
                        new
                        {
                            Id = 4,
                            MascotImageLink = "https://s1.thcdn.com/productimg/1600/1600/12024630-1024653879759849.jpg",
                            Name = "Ravenclaw"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Headmaster/Headmistress"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deputy Headmaster/Headmistress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Professor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Patron/Matron"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grounds Keeper"
                        },
                        new
                        {
                            Id = 6,
                            Name = "House Head"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Librarian"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Caretaker"
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MiddleNames")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Albus",
                            Gender = 0,
                            LastName = "Dumbledore",
                            MiddleNames = "Percival Wulfric Brian"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Minerva",
                            Gender = 1,
                            LastName = "McGonagall",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sybill",
                            Gender = 1,
                            LastName = "Trelawny",
                            MiddleNames = "Patricia"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Severus",
                            Gender = 0,
                            LastName = "Snape",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Cuthbert",
                            Gender = 0,
                            LastName = "Binns",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Charity",
                            Gender = 1,
                            LastName = "Burbage",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Alecto",
                            Gender = 1,
                            LastName = "Carrow",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Remus",
                            Gender = 0,
                            LastName = "Lupin",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Filius",
                            Gender = 0,
                            LastName = "Flitwick",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Alastor",
                            Gender = 0,
                            LastName = "Moody",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Wilhelmina",
                            Gender = 1,
                            LastName = "Grubbly-Plank",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Rubeus",
                            Gender = 0,
                            LastName = "Hagrid",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Rolanda",
                            Gender = 1,
                            LastName = "Hooch",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Horace",
                            Gender = 0,
                            LastName = "Slughorn",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Silvanus",
                            Gender = 0,
                            LastName = "Kettleburn",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Pomona",
                            Gender = 1,
                            LastName = "Sprout",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Argus",
                            Gender = 0,
                            LastName = "Filch",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Gilderoy",
                            Gender = 0,
                            LastName = "Lockhart",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Quirinus",
                            Gender = 0,
                            LastName = "Quirrell",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Poppy",
                            Gender = 1,
                            LastName = "Pomfrey",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Amycus",
                            Gender = 0,
                            LastName = "Carrow",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Firenze",
                            Gender = 0,
                            LastName = "",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Irma",
                            Gender = 1,
                            LastName = "Pince",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Aurora",
                            Gender = 1,
                            LastName = "Sinistra",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Dolores",
                            Gender = 1,
                            LastName = "Umbridge",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Septima",
                            Gender = 1,
                            LastName = "Vector",
                            MiddleNames = ""
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.StaffCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffCourse");

                    b.HasData(
                        new
                        {
                            CourseId = 3,
                            StaffId = 1
                        },
                        new
                        {
                            CourseId = 8,
                            StaffId = 25
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            StaffId = 2
                        },
                        new
                        {
                            CourseId = 1,
                            StaffId = 5
                        },
                        new
                        {
                            CourseId = 2,
                            StaffId = 6
                        },
                        new
                        {
                            CourseId = 4,
                            StaffId = 11
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 8
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 4
                        },
                        new
                        {
                            CourseId = 2,
                            StaffId = 7
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 21
                        },
                        new
                        {
                            CourseId = 11,
                            StaffId = 23
                        },
                        new
                        {
                            CourseId = 7,
                            StaffId = 9
                        },
                        new
                        {
                            CourseId = 4,
                            StaffId = 12
                        },
                        new
                        {
                            CourseId = 6,
                            StaffId = 13
                        },
                        new
                        {
                            CourseId = 4,
                            StaffId = 15
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 18
                        },
                        new
                        {
                            CourseId = 2,
                            StaffId = 19
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 19
                        },
                        new
                        {
                            CourseId = 12,
                            StaffId = 14
                        },
                        new
                        {
                            CourseId = 12,
                            StaffId = 4
                        },
                        new
                        {
                            CourseId = 9,
                            StaffId = 3
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 26
                        },
                        new
                        {
                            CourseId = 14,
                            StaffId = 27
                        },
                        new
                        {
                            CourseId = 5,
                            StaffId = 10
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.StaffRole", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("StaffId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("StaffRoles");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            StaffId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            StaffId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            StaffId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            StaffId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            StaffId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            StaffId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 13,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 16,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 12,
                            RoleId = 5
                        },
                        new
                        {
                            StaffId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            StaffId = 2,
                            RoleId = 6
                        },
                        new
                        {
                            StaffId = 4,
                            RoleId = 6
                        },
                        new
                        {
                            StaffId = 9,
                            RoleId = 6
                        },
                        new
                        {
                            StaffId = 14,
                            RoleId = 6
                        },
                        new
                        {
                            StaffId = 16,
                            RoleId = 6
                        },
                        new
                        {
                            StaffId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 23,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 24,
                            RoleId = 7
                        },
                        new
                        {
                            StaffId = 20,
                            RoleId = 4
                        },
                        new
                        {
                            StaffId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 25,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            StaffId = 26,
                            RoleId = 3
                        },
                        new
                        {
                            StaffId = 17,
                            RoleId = 8
                        },
                        new
                        {
                            StaffId = 27,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MiddleNames")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ronald",
                            HouseId = 1,
                            LastName = "Weasely",
                            MiddleNames = "Bilius"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Draco",
                            HouseId = 2,
                            LastName = "Malfoy",
                            MiddleNames = "Lucious"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Hannah",
                            HouseId = 3,
                            LastName = "Abbott",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Katie",
                            HouseId = 1,
                            LastName = "Bell",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Susan",
                            HouseId = 3,
                            LastName = "Bones",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Terry",
                            HouseId = 4,
                            LastName = "Boot",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Lavender",
                            HouseId = 1,
                            LastName = "Brown",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Cho",
                            HouseId = 4,
                            LastName = "Chang",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Michael",
                            HouseId = 4,
                            LastName = "Corner",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Justin",
                            HouseId = 3,
                            LastName = "Finch-Fletchley",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Anthony",
                            HouseId = 4,
                            LastName = "Goldstein",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Graham",
                            HouseId = 2,
                            LastName = "Pritchard",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Malcolm",
                            HouseId = 2,
                            LastName = "Baddock",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Astoria",
                            HouseId = 2,
                            LastName = "Greengrass",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Theodore",
                            HouseId = 2,
                            LastName = "Nott",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Daphne",
                            HouseId = 2,
                            LastName = "Greengrass",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Lilian",
                            HouseId = 2,
                            LastName = "Moon",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Tracey",
                            HouseId = 2,
                            LastName = "Davis",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Adrian",
                            HouseId = 2,
                            LastName = "Pucey",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Terence",
                            HouseId = 2,
                            LastName = "Higgs",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Rose",
                            HouseId = 3,
                            LastName = "Zeller",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Kevin",
                            HouseId = 3,
                            LastName = "Whitby",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Laura",
                            HouseId = 3,
                            LastName = "Madley",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Megan",
                            HouseId = 3,
                            LastName = "Jones",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Wayne",
                            HouseId = 3,
                            LastName = "Hopkins",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Owen",
                            HouseId = 3,
                            LastName = "Cauldwell",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Eleanor",
                            HouseId = 3,
                            LastName = "Branstone",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Stewart",
                            HouseId = 4,
                            LastName = "Ackerley",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Orla",
                            HouseId = 4,
                            LastName = "Quirke",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Luna",
                            HouseId = 4,
                            LastName = "Lovegood",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Lisa",
                            HouseId = 4,
                            LastName = "Turpin",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Padma",
                            HouseId = 4,
                            LastName = "Patil",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Morag",
                            HouseId = 4,
                            LastName = "McDougal",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Su",
                            HouseId = 4,
                            LastName = "Li",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Kevin",
                            HouseId = 5,
                            LastName = "Entwhistle",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Stephen",
                            HouseId = 4,
                            LastName = "Cornfoot",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Michael",
                            HouseId = 4,
                            LastName = "Corner",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Mandy",
                            HouseId = 4,
                            LastName = "Brocklehurst",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Marietta",
                            HouseId = 4,
                            LastName = "Edgecombe",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Eddie",
                            HouseId = 4,
                            LastName = "Carmichael",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Roger",
                            HouseId = 4,
                            LastName = "Davies",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Penelope",
                            HouseId = 4,
                            LastName = "Clearwater",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Mary",
                            HouseId = 1,
                            LastName = "MacDonald",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Euan",
                            HouseId = 1,
                            LastName = "Abercrombie",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Jimmy",
                            HouseId = 1,
                            LastName = "Peakes",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Natalie",
                            HouseId = 1,
                            LastName = "McDonald",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Romilda",
                            HouseId = 1,
                            LastName = "Vane",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Ginny",
                            HouseId = 1,
                            LastName = "Weasley",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Neville",
                            HouseId = 1,
                            LastName = "Longbottom",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Cormac",
                            HouseId = 1,
                            LastName = "McLaggen",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Demelza",
                            HouseId = 1,
                            LastName = "Robins",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Andrew",
                            HouseId = 1,
                            LastName = "Kirke",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Geoffrey",
                            HouseId = 1,
                            LastName = "Hooper",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Victoria",
                            HouseId = 1,
                            LastName = "Frobisher",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Jack",
                            HouseId = 1,
                            LastName = "Sloper",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Ritchie",
                            HouseId = 1,
                            LastName = "Coote",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Eloise",
                            HouseId = 5,
                            LastName = "Midgen",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Dennis",
                            HouseId = 1,
                            LastName = "Creevey",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Gregory",
                            HouseId = 2,
                            LastName = "Goyle",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Vincent",
                            HouseId = 2,
                            LastName = "Crabbe",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Ernie",
                            HouseId = 3,
                            LastName = "Macmillan",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Millicent",
                            HouseId = 2,
                            LastName = "Bulstrode",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Dean",
                            HouseId = 1,
                            LastName = "Thomas",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Blaise",
                            HouseId = 2,
                            LastName = "Zabini",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Zacharias",
                            HouseId = 3,
                            LastName = "Smith",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Pansy",
                            HouseId = 2,
                            LastName = "Parkinson",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Seamus",
                            HouseId = 1,
                            LastName = "Finnigan",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Colin",
                            HouseId = 1,
                            LastName = "Creevey",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Hermione",
                            HouseId = 1,
                            LastName = "Granger",
                            MiddleNames = ""
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Harry",
                            HouseId = 1,
                            LastName = "Potter",
                            MiddleNames = ""
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.HeadOfHouse", b =>
                {
                    b.HasOne("Hogwarts.Data.House", "House")
                        .WithMany("HeadsOfHouse")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogwarts.Data.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.StaffCourse", b =>
                {
                    b.HasOne("Hogwarts.Data.Course", "Course")
                        .WithMany("StaffCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogwarts.Data.Staff", "Staff")
                        .WithMany("StaffCourse")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.StaffRole", b =>
                {
                    b.HasOne("Hogwarts.Data.Role", "Role")
                        .WithMany("StaffRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogwarts.Data.Staff", "Staff")
                        .WithMany("StaffRoles")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.Student", b =>
                {
                    b.HasOne("Hogwarts.Data.House", "House")
                        .WithMany("Students")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
